apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
              name: http
	  livenessProbe:
	    httpGet:
	      path: {{ .Values.livenessProbe.httpGet.path }}
	      port: {{ .Values.livenessProbe.httpGet.port }}
	    initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
	    periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
	    failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
	  
	  readinessProbe:
	    httpGet:
	      path: {{ .Values.readinessProbe.httpGet.path }}
	      port: {{ .Values.readinessProbe.httpGet.port }}
	    initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
	    periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
	    failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
