name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Run tests
        run: go test ./...

      - name: Build and tag Docker image
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t tovalavatar/talonone-test:$IMAGE_TAG .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker push tovalavatar/talonone-test:$IMAGE_TAG

      - name: Update Helm image tag in values.yaml
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          echo "Updating image.tag in values.yaml to $IMAGE_TAG"
          sed -i "s/^  tag:.*$/  tag: \"$IMAGE_TAG\"/" ./helm/talonone-test/values.yaml
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add ./helm/talonone-test/values.yaml
          git commit -m "Update image tag to $IMAGE_TAG"
          git push origin main
