name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Run tests
        run: go test ./...

      - name: Build Docker image
        run: |
          docker build -t tovalavatar/talonone-test:latest .

      # Optional: You can add steps here to push image to Docker Hub if you set secrets

